In [2]:
>>> import sys
>>> print(sys.path)


['', '/home/pritesh/catkin_ws/devel/lib/python2.7/dist-packages', '/opt/ros/kinetic/lib/python2.7/dist-packages', '/home/pritesh/anaconda3/lib/python36.zip', '/home/pritesh/anaconda3/lib/python3.6', '/home/pritesh/anaconda3/lib/python3.6/lib-dynload', '/home/pritesh/.local/lib/python3.6/site-packages', '/home/pritesh/anaconda3/lib/python3.6/site-packages', '/home/pritesh/anaconda3/lib/python3.6/site-packages/Sphinx-1.5.1-py3.6.egg', '/home/pritesh/anaconda3/lib/python3.6/site-packages/IPython/extensions', '/home/pritesh/.ipython']


In [3]:
sys.path.remove('/opt/ros/kinetic/lib/python2.7/dist-packages')
print(sys.path)


['', '/home/pritesh/catkin_ws/devel/lib/python2.7/dist-packages', '/home/pritesh/anaconda3/lib/python36.zip', '/home/pritesh/anaconda3/lib/python3.6', '/home/pritesh/anaconda3/lib/python3.6/lib-dynload', '/home/pritesh/.local/lib/python3.6/site-packages', '/home/pritesh/anaconda3/lib/python3.6/site-packages', '/home/pritesh/anaconda3/lib/python3.6/site-packages/Sphinx-1.5.1-py3.6.egg', '/home/pritesh/anaconda3/lib/python3.6/site-packages/IPython/extensions', '/home/pritesh/.ipython']


In [4]:
import numpy as np
import cv2
import glob
import uuid

# termination criteria
criteria = (cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER, 30, 0.001)

# prepare object points, like (0,0,0), (1,0,0), (2,0,0) ....,(6,5,0)
objp = np.zeros((8*6,3), np.float32)
objp[:,:2] = np.mgrid[0:8,0:6].T.reshape(-1,2)

# Arrays to store object points and image points from all the images.
objpoints = [] # 3d point in real world space
imgpoints = [] # 2d points in image plane.

# images = glob.glob('selectedFeature/*.jpg')
images = glob.glob('atWork50/*.jpg')

i=0
for fname in images:
    print(fname)
    img = cv2.imread(fname)
    gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)

    # Find the chess board corners
    # Remember if it has 9x7 size then enter (8,6)
    ret, corners = cv2.findChessboardCorners(gray, (8,6),None)

    # If found, add object points, image points (after refining them)
    if ret == True:
        objpoints.append(objp)

        corners2 = cv2.cornerSubPix(gray,corners,(11,11),(-1,-1),criteria)
        imgpoints.append(corners2)

        # Draw and display the corners
        img = cv2.drawChessboardCorners(img, (8,6), corners2,ret)
        outfile = '%s/%s.jpg' % ('cbcross', 'checker' + str(fname[-6:-4]))
        cv2.imwrite(outfile,img)
        cv2.imshow('img',img)
        cv2.waitKey(500)
        i = i+1

cv2.destroyAllWindows()

atWork50/my_photo-16.jpg
atWork50/my_photo-48.jpg
atWork50/my_photo-14.jpg
atWork50/my_photo-11.jpg
atWork50/my_photo-45.jpg
atWork50/my_photo-37.jpg
atWork50/my_photo-51.jpg
atWork50/my_photo-47.jpg
atWork50/my_photo-49.jpg
atWork50/my_photo-20.jpg
atWork50/my_photo-36.jpg
atWork50/my_photo-59.jpg
atWork50/my_photo-8.jpg
atWork50/my_photo-17.jpg
atWork50/my_photo-10.jpg
atWork50/my_photo-42.jpg
atWork50/my_photo-57.jpg
atWork50/my_photo-53.jpg
atWork50/my_photo-24.jpg
atWork50/my_photo-27.jpg
atWork50/my_photo-66.jpg
atWork50/my_photo-31.jpg
atWork50/my_photo-32.jpg
atWork50/my_photo-15.jpg
atWork50/my_photo-50.jpg
atWork50/my_photo-4.jpg
atWork50/my_photo-58.jpg
atWork50/my_photo-28.jpg
atWork50/my_photo-60.jpg
atWork50/my_photo-3.jpg
atWork50/my_photo-63.jpg
atWork50/my_photo-26.jpg
atWork50/my_photo-6.jpg
atWork50/my_photo-30.jpg
atWork50/my_photo-68.jpg
atWork50/my_photo-65.jpg
atWork50/my_photo-39.jpg
atWork50/my_photo-41.jpg
atWork50/my_photo-7.jpg
atWork50/my_photo-33.jpg
atWor

In [5]:
ret, mtx, dist, rvecs, tvecs = cv2.calibrateCamera(objpoints, imgpoints, gray.shape[::-1],None,None)

In [7]:
np.round(dist,3)

array([[-0.023,  0.188,  0.002,  0.002, -0.353]])

In [8]:
mtx

array([[1.44327526e+03, 0.00000000e+00, 9.58085491e+02],
       [0.00000000e+00, 1.44302306e+03, 5.68318695e+02],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00]])

In [9]:
for i in tvecs:
    print('\lbrack',np.round(i[0][0],3),',',np.round(i[1][0],3),',',np.round(i[2][0],3),'\\rbrack \\\\')
    


\lbrack -1.844 , -3.761 , 12.458 \rbrack \\
\lbrack 4.374 , -5.65 , 22.316 \rbrack \\
\lbrack -2.08 , -3.093 , 11.215 \rbrack \\
\lbrack -6.456 , -5.092 , 18.968 \rbrack \\
\lbrack 3.172 , -2.277 , 17.385 \rbrack \\
\lbrack -5.288 , -3.189 , 20.92 \rbrack \\
\lbrack -1.498 , -3.538 , 15.429 \rbrack \\
\lbrack 4.672 , -0.635 , 21.351 \rbrack \\
\lbrack 4.48 , -3.061 , 21.528 \rbrack \\
\lbrack -0.529 , -3.042 , 13.712 \rbrack \\
\lbrack -5.544 , 1.423 , 12.126 \rbrack \\
\lbrack -2.463 , -3.495 , 17.666 \rbrack \\
\lbrack -0.018 , -3.803 , 13.752 \rbrack \\
\lbrack -4.376 , -2.67 , 21.723 \rbrack \\
\lbrack -4.354 , -2.726 , 17.396 \rbrack \\
\lbrack -4.639 , -3.008 , 14.22 \rbrack \\
\lbrack 0.47 , -3.703 , 18.625 \rbrack \\
\lbrack 0.684 , 2.05 , 20.493 \rbrack \\
\lbrack -5.878 , -2.464 , 20.765 \rbrack \\
\lbrack 1.933 , 4.151 , 18.815 \rbrack \\
\lbrack -3.493 , -2.669 , 10.278 \rbrack \\
\lbrack -2.731 , 1.539 , 8.85 \rbrack \\
\lbrack -8.05 , 0.845 , 17.014 \rbrack \\
\lbrack -1.

In [13]:
for i in rvecs:
#     print('[', np.round(i[0][0],3),',',np.round(i[1][0],3),',',np.round(i[2][0],3),']')
    print('\lbrack',np.round(i[0][0],3),',',np.round(i[1][0],3),',',np.round(i[2][0],3),'\\rbrack \\\\')

\lbrack 0.121 , -0.068 , 0.068 \rbrack \\
\lbrack -0.654 , 0.871 , 0.884 \rbrack \\
\lbrack 0.437 , 0.17 , 0.146 \rbrack \\
\lbrack 0.073 , -0.158 , 0.658 \rbrack \\
\lbrack 0.012 , -0.056 , -0.036 \rbrack \\
\lbrack -0.302 , -0.449 , 1.555 \rbrack \\
\lbrack -0.26 , -0.915 , 1.448 \rbrack \\
\lbrack 0.062 , -0.002 , -0.021 \rbrack \\
\lbrack -0.233 , 0.742 , 0.271 \rbrack \\
\lbrack -0.547 , 0.02 , 0.172 \rbrack \\
\lbrack -0.116 , -0.907 , -1.287 \rbrack \\
\lbrack -0.458 , -0.553 , 1.553 \rbrack \\
\lbrack 0.121 , 0.247 , 0.22 \rbrack \\
\lbrack 0.145 , -0.118 , -0.079 \rbrack \\
\lbrack 0.02 , -0.066 , -0.011 \rbrack \\
\lbrack -0.642 , 0.105 , 0.168 \rbrack \\
\lbrack -0.576 , -0.648 , 1.5 \rbrack \\
\lbrack -0.052 , 0.851 , -1.36 \rbrack \\
\lbrack -0.237 , -0.485 , 1.458 \rbrack \\
\lbrack 0.225 , -0.08 , -1.444 \rbrack \\
\lbrack 0.073 , -0.241 , -0.067 \rbrack \\
\lbrack -0.533 , -0.471 , -1.48 \rbrack \\
\lbrack 0.087 , 0.22 , -0.856 \rbrack \\
\lbrack 0.188 , -0.009 , 0.05 \

In [8]:
img = cv2.imread('atWork50/my_photo-56.jpg')
# img = cv2.imread('selectedFeature/2019-05-13-172802.jpg')
# img = cv2.imread('Webcam/2019-05-13-171433.jpg')
h,  w = img.shape[:2]
newcameramtx, roi=cv2.getOptimalNewCameraMatrix(mtx,dist,(w,h),1,(w,h))
cv2.imshow('img',img)
cv2.waitKey(2000)
cv2.destroyAllWindows()

In [9]:
# undistort Using cv2.undistort()
i = 0
dst = cv2.undistort(img, mtx, dist, None, newcameramtx)

# crop the image
x,y,w,h = roi
dst = dst[y:y+h, x:x+w]
cv2.imwrite('result/calibrated.png',dst)
cv2.imwrite('result/original.png',img)
# for i in range(6):
#     if(i%2==0):
#         cv2.imshow('opencvData/left12.jpg',img)
#         cv2.waitKey(1000)
#     else:
#         cv2.imshow('opencvData/left12.jpg',dst)
#         cv2.waitKey(1000)
# cv2.destroyAllWindows()

True

In [45]:
# undistort Using cv2.undistort()
mapx,mapy = cv2.initUndistortRectifyMap(mtx,dist,None,newcameramtx,(w,h),5)
dst = cv2.remap(img,mapx,mapy,cv2.INTER_LINEAR)

# crop the image
x,y,w,h = roi
dst = dst[y:y+h, x:x+w]
# cv2.imwrite('calibresult.png',dst)
cv2.imwrite('result/calibresult.png',dst)
cv2.imwrite('result/calibresult1.png',img)
#Loop to look the images
# for i in range(6):
#     if(i%2==0):
#         cv2.imshow('opencvData/left12.jpg',img)
#         cv2.waitKey(1000)
#     else:
#         cv2.imshow('opencvData/left12.jpg',dst)
#         cv2.waitKey(1000)
# cv2.destroyAllWindows()

True

In [41]:
# To save the result of camera matrix and distortion coefficient
np.savetxt("result.txt", mtx, delimiter=',', newline='\n')
np.savetxt("result.txt", dist, delimiter=',')

https://dataplatform.cloud.ibm.com/data/notebooks/converter/jupyter/0849b7a8-d79b-4dc9-a104-0020b2b350f7?access_token=b2abf8704d456ae2254a32746f4af0e0d9eed41a8ffebdd3cd16dec20dcbd592

In [10]:
tot_error = 0
for i in range(len(objpoints)):
    imgpoints2, _ = cv2.projectPoints(objpoints[i], rvecs[i], tvecs[i], mtx, dist)
    error = cv2.norm(imgpoints[i],imgpoints2, cv2.NORM_L2)/len(imgpoints2)
    tot_error += error

print ("total error: ", tot_error/len(objpoints))

# according to https://gist.github.com/TimSC/bf14579149b4d36e3558
tot_error = 0
for i in range(len(objpoints)):
    imgpoints2, _ = cv2.projectPoints(objpoints[i], rvecs[i], tvecs[i], mtx, dist)
    error = cv2.norm(imgpoints[i],imgpoints2, cv2.NORM_L2)/len(imgpoints2)
    tot_error += error*error

print ("total error sqrt: ", np.sqrt(tot_error/len(objpoints)))

total error:  0.04494475539817287
total error sqrt:  0.04795749659097786


error with equal distance = 0.2545
error with unequal distance = 0.2324

In [6]:
def draw(img, corners, imgpts):
    corner = tuple(corners[0].ravel())
    img = cv2.line(img, corner, tuple(imgpts[0].ravel()), (255,0,0), 5)
    img = cv2.line(img, corner, tuple(imgpts[1].ravel()), (0,255,0), 5)
    img = cv2.line(img, corner, tuple(imgpts[2].ravel()), (0,0,255), 5)
    return img

In [18]:
criteria = (cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER, 30, 0.001)
objp = np.zeros((6*7,3), np.float32)
objp[:,:2] = np.mgrid[0:7,0:6].T.reshape(-1,2)

axis = np.float32([[3,0,0], [0,3,0], [0,0,-3]]).reshape(-1,3)

In [36]:
for fname in glob.glob("result/*.png"):
    img = cv2.imread(fname)
    gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
    ret, corners = cv2.findChessboardCorners(gray, (8,6),None)
    print("finding corner")
    if ret == True:
        corners2 = cv2.cornerSubPix(gray,corners,(11,11),(-1,-1),criteria)

        # Find the rotation and translation vectors.
        rvecs, tvecs, inliers = cv2.solvePnPRansac(objp, corners2, mtx[0], dist)

        # project 3D points to image plane
        imgpts, jac = cv2.projectPoints(axis, rvecs, tvecs, mtx, dist)

        img = draw(img,corners2,imgpts)
        cv2.imshow('img',img)
        k = cv2.waitKey(0) & 0xff
        if k == 's':
            cv2.imwrite(fname[:6]+'.png', img)

cv2.destroyAllWindows()

finding corner


error: OpenCV(4.1.0) /io/opencv/modules/calib3d/src/solvepnp.cpp:280: error: (-215:Assertion failed) npoints >= 4 && npoints == std::max(ipoints.checkVector(2, CV_32F), ipoints.checkVector(2, CV_64F)) in function 'solvePnPRansac'


In [25]:
for fname in glob.glob('left*.jpg'):
    img = cv2.imread(fname)
    gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
    ret, corners = cv2.findChessboardCorners(gray, (7,6),None)

    if ret == True:
        corners2 = cv2.cornerSubPix(gray,corners,(11,11),(-1,-1),criteria)

        # Find the rotation and translation vectors.
        rvecs, tvecs, inliers = cv2.solvePnPRansac(objp, corners2, mtx[0], dist[0])

        # project 3D points to image plane
        imgpts, jac = cv2.projectPoints(axis, rvecs, tvecs, mtx, dist)

        img = draw(img,corners2,imgpts)
        cv2.imshow('img',img)
        k = cv2.waitKey(0) & 0xff
        if k == 's':
            cv2.imwrite(fname[:6]+'.png', img)

cv2.destroyAllWindows()

In [28]:
dist[0]


array([-0.02308331,  0.18778268,  0.00185078,  0.00165127, -0.35331354])